###
# @name UserEntries
# @lang lua
< {%

local year=2025
local month=1
local time_entry_date = os.time({year=year, month=month, day=0})
local start_of_month = os.date("%Y-%m-01", time_entry_date).."T00:00:00Z"
local end_of_month = os.date("%Y-%m-%d", time_entry_date).."T23:59:59Z"

request.variables.set("start_date", start_of_month)
request.variables.set("end_date", end_of_month)
%}

GET https://httpbin.org/get?user={{username}}&start={{start_date}}&end={{end_date}}
x-api-key: {{api_key}}
content-type: application/json

# @lang=lua
> {%
-- require("user.functions").rest_nvim_dump_response(response.body, response.headers["content-type"])
%}


###
# @name BasicAuth
# @lang lua
< {%

local env_username = request.variables.get("username")
local env_password = request.variables.get("password")
local basic_auth_token = vim.base64.encode(env_username .. ":" .. env_password)

request.variables.set("basic_auth_token", basic_auth_token)
%}

GET https://httpbin.org/basic-auth/{{username}}/{{password}}
Accept: application/json
Authorization: Basic {{basic_auth_token}}


###
# @name SetCookies
GET https://httpbin.org/cookies/set/theme/light


###
# @name GetCookies
GET https://httpbin.org/cookies


