# Catppuccin Mocha - https://catppuccin.com/palette
set -g @custom_default "#1e1e2e" # base
set -g @custom_black "#11111b"   # crust
set -g @custom_accent "#b4befe"  # lavender
set -g @custom_grey "#bac2de"    # subtext1
set -g @custom_white "#cdd6f4"   # text
