# Catppuccin Latte - https://catppuccin.com/palette
set -g @custom_default "#eff1f5" # base
set -g @custom_black "#4c4f69"   # text
set -g @custom_accent "#7287fd"  # lavender
set -g @custom_grey "#5c5f77"    # subtext1
set -g @custom_white "#acb0be"   # surface2
