# Idle configuration, ported from the swayidle setup in ~/dotfiles/.config/sway/config
#
# Read https://wiki.hypr.land/Hypr-Ecosystem/hypridle/ for a complete reference.

general {
    # Avoid starting multiple hyprlock instances
    lock_cmd = pidof hyprlock || hyprlock
    # Lock before the computer goes to sleep
    before_sleep_cmd = loginctl lock-session
    # Avoid having to press a key twice to turn the display back on
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Lock the screen after 900 seconds of inactivity
listener {
    timeout = 900
    on-timeout = loginctl lock-session
}

# Turn off the displays after another 300 seconds, back on when resumed
listener {
    timeout = 1200
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
