import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm256-color"

[window]
# opacity = 0.9
startup_mode = "Maximized"

[scrolling]
history = 50000

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 8

# [colors]
# transparent_background_colors = true

[cursor]
style = { shape = "Beam", blinking = "Always" }
